// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVw7L-5uLro62qXH56zjcN20lCpQllGIc',
    appId: '1:651771240710:web:b9065dd16fb1d7761afe87',
    messagingSenderId: '651771240710',
    projectId: 'ctse-pms-app',
    authDomain: 'ctse-pms-app.firebaseapp.com',
    storageBucket: 'ctse-pms-app.appspot.com',
    measurementId: 'G-5DQW6FRQN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyZ8npcV9W9U4n7n3fTR3ovGToCP6L3VI',
    appId: '1:651771240710:android:041a1d6ab3a029d61afe87',
    messagingSenderId: '651771240710',
    projectId: 'ctse-pms-app',
    storageBucket: 'ctse-pms-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnjwx0zF78kfSdEG6Dm2bTixj5wAsHRGM',
    appId: '1:651771240710:ios:1e94f5c68b528c6e1afe87',
    messagingSenderId: '651771240710',
    projectId: 'ctse-pms-app',
    storageBucket: 'ctse-pms-app.appspot.com',
    iosClientId: '651771240710-7cnh2t9fkp756s9g432kjqdu19601l8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.arazMobileApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnjwx0zF78kfSdEG6Dm2bTixj5wAsHRGM',
    appId: '1:651771240710:ios:1e94f5c68b528c6e1afe87',
    messagingSenderId: '651771240710',
    projectId: 'ctse-pms-app',
    storageBucket: 'ctse-pms-app.appspot.com',
    iosClientId: '651771240710-7cnh2t9fkp756s9g432kjqdu19601l8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.arazMobileApplication',
  );
}
